"""
LLM-based communication formatter for SentinelAI verification results.

The verification process is already complete before this service runs.

The formatter may:

- improve clarity,
- organize the verification assessment,
- explain checks, findings, conditions, and confidence,
- translate structured verification into readable language.

The formatter may not:

- perform new verification,
- introduce new findings,
- remove existing findings,
- change verification status,
- change verification confidence,
- alter conditions,
- revise the planning subject,
- make governance decisions.

Sentinel verifies first and communicates second.
"""

from __future__ import annotations

import os

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field

from app.services.cognition.verification.models import (
    VerificationResult,
)


load_dotenv()


class VerificationNarrative(BaseModel):
    """
    Structured prose generated by the verification communication layer.

    These fields explain an authoritative VerificationResult but never
    replace or modify the underlying verification judgment.
    """

    answer: str = Field(
        description=(
            "A concise explanation of the authoritative verification "
            "status. Do not change the recorded status."
        ),
    )

    subject_explanation: str = Field(
        description=(
            "A concise explanation of what cognitive subject was "
            "verified."
        ),
    )

    checks_explanation: str = Field(
        description=(
            "A clear explanation of the verification checks and "
            "coverage already recorded."
        ),
    )

    findings_explanation: str = Field(
        description=(
            "A concise explanation of the recorded findings. "
            "Do not add, remove, or reinterpret findings."
        ),
    )

    conditions_explanation: str = Field(
        description=(
            "A clear explanation of the recorded verification "
            "conditions. Do not invent new conditions."
        ),
    )

    confidence_explanation: str = Field(
        description=(
            "A clear explanation of verification confidence. "
            "Do not change its score, level, factors, or uncertainty."
        ),
    )


class FormattedVerificationResponse(BaseModel):
    """
    Communication result returned after formatting.

    Authoritative verification fields are copied directly from the
    VerificationResult. Only narrative fields are model-generated.
    """

    answer: str

    subject_explanation: str

    checks_explanation: str

    findings_explanation: str

    conditions_explanation: str

    confidence_explanation: str

    status: str

    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
    )

    confidence_level: str

    findings_count: int = Field(
        default=0,
        ge=0,
    )

    blocking_findings_count: int = Field(
        default=0,
        ge=0,
    )

    conditions: list[str] = Field(
        default_factory=list,
    )

    source_check_count: int = Field(
        default=0,
        ge=0,
    )

    coverage_score: float = Field(
        default=0.0,
        ge=0.0,
        le=1.0,
    )

    completed_categories: list[str] = Field(
        default_factory=list,
    )

    skipped_categories: list[str] = Field(
        default_factory=list,
    )

    uncertainty: list[str] = Field(
        default_factory=list,
    )

    verification_trace: list[str] = Field(
        default_factory=list,
    )


class VerificationResultPayload(BaseModel):
    """
    Internal serialization boundary for formatter input.
    """

    payload: dict


class LLMVerificationFormatter:
    """
    Convert a completed VerificationResult into professional language.

    This service is intentionally downstream from deterministic
    verification. It cannot modify Sentinel's authoritative judgment.
    """

    def __init__(
        self,
        *,
        model: str = "gpt-4.1-mini",
    ):
        api_key = os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise RuntimeError(
                "OPENAI_API_KEY is not configured."
            )

        self.client = OpenAI(
            api_key=api_key,
        )

        self.model = model

    @staticmethod
    def _system_message() -> str:
        return (
            "You are SentinelAI's verification communication layer. "
            "The verification operation has already been completed by "
            "deterministic services. Your only responsibility is to "
            "explain the supplied structured result clearly and "
            "professionally. Do not perform new verification. Do not "
            "introduce, remove, or modify findings, conditions, checks, "
            "confidence values, verification status, or uncertainty. "
            "Do not revise the planning subject. Do not make approval "
            "or execution decisions. Preserve uncertainty exactly."
        )

    @staticmethod
    def _formatter_payload(
        result: VerificationResult,
    ) -> str:
        """
        Serialize only authoritative information needed for communication.
        """

        payload = {
            "subject": {
                "subject_type": (
                    result.subject.subject_type.value
                ),
                "objective": result.subject.objective,
                "subject_status": (
                    result.subject.subject_status
                ),
                "subject_confidence_score": (
                    result.subject.subject_confidence_score
                ),
                "subject_confidence_level": (
                    result.subject.subject_confidence_level
                ),
                "strategy_name": (
                    result.subject.strategy_name
                ),
                "step_count": len(
                    result.subject.step_ids
                ),
                "dependency_count": len(
                    result.subject.dependency_ids
                ),
                "risk_count": len(
                    result.subject.risk_ids
                ),
                "constraint_count": (
                    result.subject.constraint_count
                ),
            },
            "verification": {
                "scope": result.scope.value,
                "status": result.status.value,
                "coverage": {
                    "requested_categories": [
                        category.value
                        for category
                        in result.coverage.requested_categories
                    ],
                    "completed_categories": [
                        category.value
                        for category
                        in result.coverage.completed_categories
                    ],
                    "skipped_categories": [
                        category.value
                        for category
                        in result.coverage.skipped_categories
                    ],
                    "check_count": (
                        result.coverage.check_count
                    ),
                    "passed_count": (
                        result.coverage.passed_count
                    ),
                    "conditional_count": (
                        result.coverage.conditional_count
                    ),
                    "failed_count": (
                        result.coverage.failed_count
                    ),
                    "unverifiable_count": (
                        result.coverage.unverifiable_count
                    ),
                    "not_applicable_count": (
                        result.coverage.not_applicable_count
                    ),
                    "coverage_score": (
                        result.coverage.coverage_score
                    ),
                },
                "confidence": {
                    "score": result.confidence.score,
                    "level": (
                        result.confidence.level.value
                    ),
                    "basis": result.confidence.basis,
                    "factors": [
                        factor.model_dump()
                        for factor in result.confidence.factors
                    ],
                    "uncertainty": (
                        result.confidence.uncertainty
                    ),
                },
                "findings": [
                    {
                        "finding_id": finding.finding_id,
                        "category": finding.category.value,
                        "title": finding.title,
                        "description": finding.description,
                        "severity": finding.severity.value,
                        "blocking": finding.blocking,
                        "required_resolution": (
                            finding.required_resolution
                        ),
                        "affected_object_ids": (
                            finding.affected_object_ids
                        ),
                    }
                    for finding in result.findings
                ],
                "conditions": result.conditions,
                "checks": [
                    {
                        "check_id": check.check_id,
                        "category": check.category.value,
                        "outcome": check.outcome.value,
                        "severity": check.severity.value,
                        "observation": check.observation,
                        "recommendation": (
                            check.recommendation
                        ),
                        "uncertainty": (
                            check.uncertainty
                        ),
                    }
                    for check in result.checks
                ],
                "verification_trace": (
                    result.verification_trace
                ),
            },
        }

        return VerificationResultPayload(
            payload=payload
        ).model_dump_json(indent=2)

    @staticmethod
    def _deterministic_response(
        result: VerificationResult,
    ) -> FormattedVerificationResponse:
        """
        Produce a safe deterministic representation.

        This is useful when the formatter should not need generative
        interpretation, and it establishes a stable fallback boundary.
        """

        blocking_count = sum(
            1
            for finding in result.findings
            if finding.blocking
        )

        if result.findings:
            findings_explanation = (
                f"Verification recorded {len(result.findings)} "
                f"finding(s), including {blocking_count} blocking "
                "finding(s)."
            )
        else:
            findings_explanation = (
                "Verification recorded no findings."
            )

        if result.conditions:
            conditions_explanation = (
                f"Verification recorded {len(result.conditions)} "
                "condition(s) that remain visible in the "
                "authoritative result."
            )
        else:
            conditions_explanation = (
                "Verification recorded no outstanding conditions."
            )

        return FormattedVerificationResponse(
            answer=(
                "Verification completed with status "
                f"'{result.status.value}'."
            ),
            subject_explanation=(
                "Sentinel verified the planning result for objective: "
                f"{result.subject.objective}"
            ),
            checks_explanation=(
                f"{result.coverage.check_count} verification check(s) "
                "were recorded across "
                f"{len(result.coverage.completed_categories)} "
                "completed verification category or categories."
            ),
            findings_explanation=findings_explanation,
            conditions_explanation=conditions_explanation,
            confidence_explanation=(
                "Verification confidence is "
                f"{result.confidence.level.value} "
                f"({result.confidence.score:.3f}). "
                f"{result.confidence.basis}"
            ),
            status=result.status.value,
            confidence_score=result.confidence.score,
            confidence_level=(
                result.confidence.level.value
            ),
            findings_count=len(
                result.findings
            ),
            blocking_findings_count=blocking_count,
            conditions=result.conditions,
            source_check_count=(
                result.coverage.check_count
            ),
            coverage_score=(
                result.coverage.coverage_score
            ),
            completed_categories=[
                category.value
                for category
                in result.coverage.completed_categories
            ],
            skipped_categories=[
                category.value
                for category
                in result.coverage.skipped_categories
            ],
            uncertainty=(
                result.confidence.uncertainty
            ),
            verification_trace=(
                result.verification_trace
            ),
        )

    def format(
        self,
        result: VerificationResult,
    ) -> FormattedVerificationResponse:
        """
        Format one completed verification operation.

        Every authoritative verification field returned here is copied
        directly from the VerificationResult.
        """

        completion = self.client.chat.completions.parse(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": self._system_message(),
                },
                {
                    "role": "user",
                    "content": (
                        "Format the following completed SentinelAI "
                        "verification result. Preserve every "
                        "authoritative judgment exactly.\n\n"
                        f"{self._formatter_payload(result)}"
                    ),
                },
            ],
            response_format=VerificationNarrative,
            temperature=0.2,
        )

        message = completion.choices[0].message

        if message.refusal:
            return self._deterministic_response(
                result
            )

        narrative = message.parsed

        if narrative is None:
            return self._deterministic_response(
                result
            )

        blocking_count = sum(
            1
            for finding in result.findings
            if finding.blocking
        )

        return FormattedVerificationResponse(
            answer=narrative.answer,
            subject_explanation=(
                narrative.subject_explanation
            ),
            checks_explanation=(
                narrative.checks_explanation
            ),
            findings_explanation=(
                narrative.findings_explanation
            ),
            conditions_explanation=(
                narrative.conditions_explanation
            ),
            confidence_explanation=(
                narrative.confidence_explanation
            ),
            status=result.status.value,
            confidence_score=(
                result.confidence.score
            ),
            confidence_level=(
                result.confidence.level.value
            ),
            findings_count=len(
                result.findings
            ),
            blocking_findings_count=blocking_count,
            conditions=result.conditions,
            source_check_count=(
                result.coverage.check_count
            ),
            coverage_score=(
                result.coverage.coverage_score
            ),
            completed_categories=[
                category.value
                for category
                in result.coverage.completed_categories
            ],
            skipped_categories=[
                category.value
                for category
                in result.coverage.skipped_categories
            ],
            uncertainty=(
                result.confidence.uncertainty
            ),
            verification_trace=(
                result.verification_trace
            ),
        )
