"""
Explainable confidence assessment for SentinelAI reasoning.

Confidence is derived from inspectable evidence characteristics rather
than copied directly from retrieval similarity or generated by an LLM.

The score represents the strength of support available for a candidate
inference. It does not represent universal certainty or objective truth.
"""

from __future__ import annotations

from statistics import mean

from app.services.cognition.reasoning.models import (
    ConfidenceAssessment,
    ConfidenceFactor,
    ConfidenceLevel,
    EvidenceBundle,
    Inference,
)


class ConfidenceEngine:
    """
    Calculate transparent confidence for a candidate inference.

    Every factor produces:

    - a bounded contribution,
    - a human-readable explanation,
    - an inspectable effect on the final score.
    """

    @staticmethod
    def _clamp(
        value: float,
        minimum: float = 0.0,
        maximum: float = 1.0,
    ) -> float:
        return max(
            minimum,
            min(value, maximum),
        )

    @staticmethod
    def _confidence_level(
        score: float,
    ) -> ConfidenceLevel:
        if score >= 0.80:
            return ConfidenceLevel.HIGH

        if score >= 0.60:
            return ConfidenceLevel.MODERATE

        return ConfidenceLevel.LOW

    @staticmethod
    def _evidence_lookup(
        evidence: EvidenceBundle,
    ) -> dict[str, object]:
        """
        Build a lookup table for every evidence item with an identity.

        The value remains the EvidenceItem itself, but object is used
        here to avoid coupling this helper to one disposition list.
        """

        lookup: dict[str, object] = {}

        all_items = (
            evidence.supporting
            + evidence.conflicting
            + evidence.contextual
            + evidence.unknown
        )

        for index, item in enumerate(
            all_items,
            start=1,
        ):
            evidence_id = item.source.metadata.get(
                "evidence_id"
            )

            if not evidence_id:
                document_identity = (
                    item.source.document_id
                    or item.source.file_hash
                    or item.source.filename
                    or "unknown-document"
                )

                chunk_identity = (
                    item.source.chunk_index
                    if item.source.chunk_index is not None
                    else index
                )

                evidence_id = (
                    f"{document_identity}:{chunk_identity}"
                )

            lookup[str(evidence_id)] = item

        return lookup

    @classmethod
    def _supporting_items(
        cls,
        inference: Inference,
        evidence: EvidenceBundle,
    ) -> list:
        lookup = cls._evidence_lookup(evidence)

        return [
            lookup[evidence_id]
            for evidence_id in (
                inference.supporting_evidence_ids
            )
            if evidence_id in lookup
        ]

    @staticmethod
    def _unique_document_count(
        items: list,
    ) -> int:
        identities = {
            (
                item.source.document_id
                or item.source.file_hash
                or item.source.filename
            )
            for item in items
            if (
                item.source.document_id
                or item.source.file_hash
                or item.source.filename
            )
        }

        return len(identities)

    @staticmethod
    def _unique_domain_count(
        items: list,
    ) -> int:
        return len({
            item.source.module.casefold()
            for item in items
            if item.source.module
        })

    @staticmethod
    def _average_relevance(
        items: list,
    ) -> float:
        if not items:
            return 0.0

        return mean(
            item.relevance_score
            for item in items
        )

    @classmethod
    def _relevance_factor(
        cls,
        items: list,
    ) -> ConfidenceFactor:
        average_score = cls._average_relevance(items)

        contribution = (
            cls._clamp(average_score) * 0.35
        )

        return ConfidenceFactor(
            name="retrieval_relevance",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                "Supporting evidence has an average retrieval "
                f"relevance of {average_score:.3f}."
            ),
        )

    @classmethod
    def _volume_factor(
        cls,
        items: list,
    ) -> ConfidenceFactor:
        support_ratio = cls._clamp(
            len(items) / 5,
        )

        contribution = support_ratio * 0.20

        return ConfidenceFactor(
            name="evidence_volume",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                f"{len(items)} evidence item"
                f"{'' if len(items) == 1 else 's'} "
                "support the candidate inference."
            ),
        )

    @classmethod
    def _independence_factor(
        cls,
        items: list,
    ) -> ConfidenceFactor:
        document_count = (
            cls._unique_document_count(items)
        )

        independence_ratio = cls._clamp(
            document_count / 3,
        )

        contribution = (
            independence_ratio * 0.20
        )

        return ConfidenceFactor(
            name="source_independence",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                "Supporting evidence spans "
                f"{document_count} independent document"
                f"{'' if document_count == 1 else 's'}."
            ),
        )

    @classmethod
    def _domain_coherence_factor(
        cls,
        items: list,
    ) -> ConfidenceFactor:
        domain_count = cls._unique_domain_count(
            items
        )

        if not items:
            contribution = 0.0
            explanation = (
                "No supporting evidence was available "
                "for domain evaluation."
            )
        elif domain_count == 0:
            contribution = 0.0
            explanation = (
                "Supporting evidence does not contain "
                "canonical domain metadata."
            )
        elif domain_count == 1:
            contribution = 0.10
            explanation = (
                "All supporting evidence belongs to one "
                "coherent operational domain."
            )
        else:
            contribution = 0.06
            explanation = (
                "Supporting evidence spans multiple domains. "
                "This may improve breadth but requires "
                "cross-domain interpretation."
            )

        return ConfidenceFactor(
            name="domain_coherence",
            contribution=contribution,
            explanation=explanation,
        )

    @staticmethod
    def _inference_support_factor(
        inference: Inference,
    ) -> ConfidenceFactor:
        contribution = (
            max(
                0.0,
                min(
                    inference.confidence_score,
                    1.0,
                ),
            )
            * 0.15
        )

        return ConfidenceFactor(
            name="inference_support",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                "The deterministic inference engine assigned "
                f"a support score of "
                f"{inference.confidence_score:.3f}."
            ),
        )

    @staticmethod
    def _conflict_factor(
        inference: Inference,
        evidence: EvidenceBundle,
    ) -> ConfidenceFactor:
        conflict_count = max(
            len(
                inference.conflicting_evidence_ids
            ),
            len(evidence.conflicting),
        )

        penalty = min(
            conflict_count * 0.10,
            0.30,
        )

        return ConfidenceFactor(
            name="conflicting_evidence",
            contribution=round(
                -penalty,
                4,
            ),
            explanation=(
                f"{conflict_count} conflicting evidence item"
                f"{'' if conflict_count == 1 else 's'} "
                "must be considered."
            ),
        )

    @staticmethod
    def _gap_factor(
        evidence: EvidenceBundle,
    ) -> ConfidenceFactor:
        gap_count = len(evidence.gaps)

        penalty = min(
            gap_count * 0.06,
            0.24,
        )

        return ConfidenceFactor(
            name="evidence_gaps",
            contribution=round(
                -penalty,
                4,
            ),
            explanation=(
                f"{gap_count} unresolved evidence gap"
                f"{'' if gap_count == 1 else 's'} "
                "remain."
            ),
        )

    @staticmethod
    def _unknown_factor(
        evidence: EvidenceBundle,
    ) -> ConfidenceFactor:
        unknown_count = len(evidence.unknown)

        penalty = min(
            unknown_count * 0.03,
            0.15,
        )

        return ConfidenceFactor(
            name="unknown_evidence",
            contribution=round(
                -penalty,
                4,
            ),
            explanation=(
                f"{unknown_count} retrieved evidence item"
                f"{'' if unknown_count == 1 else 's'} "
                "could not be interpreted."
            ),
        )

    @staticmethod
    def _uncertainty(
        *,
        inference: Inference,
        evidence: EvidenceBundle,
        supporting_items: list,
    ) -> list[str]:
        uncertainty = list(
            inference.limitations
        )

        if not supporting_items:
            uncertainty.append(
                "No supporting evidence identities could "
                "be resolved from the evidence bundle."
            )

        if evidence.gaps:
            uncertainty.extend(
                gap.description
                for gap in evidence.gaps
            )

        if evidence.conflicting:
            uncertainty.append(
                "Explicit conflicting evidence remains "
                "unresolved."
            )

        deduplicated: list[str] = []
        seen: set[str] = set()

        for statement in uncertainty:
            cleaned = str(statement).strip()

            if not cleaned:
                continue

            identity = cleaned.casefold()

            if identity in seen:
                continue

            seen.add(identity)
            deduplicated.append(cleaned)

        return deduplicated

    @staticmethod
    def _basis(
        *,
        score: float,
        supporting_items: list,
        evidence: EvidenceBundle,
    ) -> str:
        document_count = (
            ConfidenceEngine._unique_document_count(
                supporting_items
            )
        )

        return (
            f"Confidence is based on "
            f"{len(supporting_items)} supporting evidence "
            f"item{'' if len(supporting_items) == 1 else 's'} "
            f"from {document_count} document"
            f"{'' if document_count == 1 else 's'}, "
            f"with {len(evidence.conflicting)} conflicting "
            f"item{'' if len(evidence.conflicting) == 1 else 's'} "
            f"and {len(evidence.gaps)} unresolved "
            f"gap{'' if len(evidence.gaps) == 1 else 's'}. "
            f"The resulting support score is {score:.3f}."
        )

    def assess(
        self,
        *,
        inference: Inference,
        evidence: EvidenceBundle,
    ) -> ConfidenceAssessment:
        """
        Produce an explainable confidence assessment.

        Scores are derived entirely from structured evidence and
        deterministic inference metadata.
        """

        supporting_items = self._supporting_items(
            inference,
            evidence,
        )

        factors = [
            self._relevance_factor(
                supporting_items
            ),
            self._volume_factor(
                supporting_items
            ),
            self._independence_factor(
                supporting_items
            ),
            self._domain_coherence_factor(
                supporting_items
            ),
            self._inference_support_factor(
                inference
            ),
            self._conflict_factor(
                inference,
                evidence,
            ),
            self._gap_factor(evidence),
            self._unknown_factor(evidence),
        ]

        score = round(
            self._clamp(
                sum(
                    factor.contribution
                    for factor in factors
                )
            ),
            3,
        )

        return ConfidenceAssessment(
            score=score,
            level=self._confidence_level(
                score
            ),
            basis=self._basis(
                score=score,
                supporting_items=(
                    supporting_items
                ),
                evidence=evidence,
            ),
            factors=factors,
            uncertainty=self._uncertainty(
                inference=inference,
                evidence=evidence,
                supporting_items=(
                    supporting_items
                ),
            ),
        )
