"""
LLM-based communication formatter for SentinelAI reasoning results.

The reasoning process is already complete before this service runs.

The formatter may:

- improve clarity,
- organize the explanation,
- translate structured reasoning into readable language.

The formatter may not:

- introduce new evidence,
- change the selected conclusion,
- modify confidence,
- remove limitations,
- invent assumptions,
- alter the recommended next step.

Sentinel reasons first and communicates second.
"""

from __future__ import annotations

import os

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field

from app.services.cognition.reasoning.models import (
    ReasoningResult,
)


load_dotenv()


class ReasoningNarrative(BaseModel):
    """
    Structured prose generated by the communication layer.

    These fields explain an authoritative ReasoningResult but do not
    replace or modify its underlying evidence, confidence, or conclusion.
    """

    answer: str = Field(
        description=(
            "A clear explanation of the authoritative conclusion. "
            "Do not add claims absent from the reasoning result."
        )
    )

    evidence_explanation: str = Field(
        description=(
            "A concise explanation of how the recorded evidence "
            "supports or limits the conclusion."
        )
    )

    confidence_explanation: str = Field(
        description=(
            "A clear explanation of the existing confidence assessment. "
            "Do not change its score or level."
        )
    )

    limitations_explanation: str = Field(
        description=(
            "A concise explanation of the recorded limitations and "
            "missing information."
        )
    )

    next_step_explanation: str = Field(
        description=(
            "A clear presentation of the recorded recommended next step. "
            "Do not replace it with a different action."
        )
    )


class FormattedReasoningResponse(BaseModel):
    """
    Final communication response returned after formatting.

    Authoritative reasoning fields are copied directly from the original
    ReasoningResult. Only the narrative fields are model-generated.
    """

    answer: str

    conclusion: str | None = None

    evidence_explanation: str

    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
    )

    confidence_level: str

    confidence_explanation: str

    limitations: list[str] = Field(
        default_factory=list,
    )

    limitations_explanation: str

    missing_information: list[str] = Field(
        default_factory=list,
    )

    recommended_next_step: str | None = None

    next_step_explanation: str

    source_count: int = 0
    document_count: int = 0
    domain_count: int = 0

    reasoning_trace: list[str] = Field(
        default_factory=list,
    )

    status: str


class LLMReasoningFormatter:
    """
    Convert a completed ReasoningResult into professional language.

    This service is intentionally downstream from the deterministic
    reasoning engine. It cannot change Sentinel's authoritative judgment.
    """

    def __init__(
        self,
        *,
        model: str = "gpt-4.1-mini",
    ):
        api_key = os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise RuntimeError(
                "OPENAI_API_KEY is not configured."
            )

        self.client = OpenAI(
            api_key=api_key,
        )

        self.model = model

    @staticmethod
    def _system_message() -> str:
        return (
            "You are SentinelAI's reasoning communication layer. "
            "The reasoning operation has already been completed by "
            "deterministic services. Your only responsibility is to "
            "explain the supplied structured result clearly and "
            "professionally. Do not introduce new evidence, facts, "
            "assumptions, conclusions, confidence values, limitations, "
            "or recommended actions. Preserve uncertainty. If the result "
            "contains insufficient evidence, state that plainly."
        )

    @staticmethod
    def _formatter_payload(
        result: ReasoningResult,
    ) -> str:
        """
        Serialize only the information needed for communication.

        Raw vector objects and hidden processing details are never sent
        to the formatter.
        """

        conclusion = result.conclusion

        if conclusion is None:
            payload = {
                "question": result.question,
                "status": result.status,
                "conclusion": None,
                "evidence": {
                    "source_count": (
                        result.evidence.source_count
                    ),
                    "document_count": (
                        result.evidence.document_count
                    ),
                    "domain_count": (
                        result.evidence.domain_count
                    ),
                    "gaps": [
                        gap.model_dump()
                        for gap in result.evidence.gaps
                    ],
                },
                "reasoning_trace": (
                    result.reasoning_trace
                ),
            }
        else:
            payload = {
                "question": result.question,
                "status": result.status,
                "conclusion": {
                    "statement": conclusion.statement,
                    "evidence_summary": (
                        conclusion.evidence_summary
                    ),
                    "inference_summary": (
                        conclusion.inference_summary
                    ),
                    "confidence": {
                        "score": (
                            conclusion.confidence.score
                        ),
                        "level": (
                            conclusion.confidence.level.value
                        ),
                        "basis": (
                            conclusion.confidence.basis
                        ),
                        "uncertainty": (
                            conclusion.confidence.uncertainty
                        ),
                    },
                    "limitations": (
                        conclusion.limitations
                    ),
                    "alternatives": (
                        conclusion.alternatives
                    ),
                    "missing_information": (
                        conclusion.missing_information
                    ),
                    "recommended_next_step": (
                        conclusion.recommended_next_step
                    ),
                },
                "evidence": {
                    "source_count": (
                        result.evidence.source_count
                    ),
                    "document_count": (
                        result.evidence.document_count
                    ),
                    "domain_count": (
                        result.evidence.domain_count
                    ),
                    "gaps": [
                        gap.model_dump()
                        for gap in result.evidence.gaps
                    ],
                },
                "reasoning_trace": (
                    result.reasoning_trace
                ),
            }

        return ReasoningResultPayload(
            payload=payload
        ).model_dump_json(indent=2)

    @staticmethod
    def _fallback_response(
        result: ReasoningResult,
    ) -> FormattedReasoningResponse:
        """
        Produce a deterministic response when no conclusion exists.

        Insufficient evidence does not require an LLM call.
        """

        return FormattedReasoningResponse(
            answer=(
                "Sentinel could not produce a supported conclusion "
                "from the available evidence."
            ),
            conclusion=None,
            evidence_explanation=(
                f"{result.evidence.source_count} evidence source(s) "
                "were analyzed, but no sufficiently supported "
                "candidate inference was produced."
            ),
            confidence_score=0.0,
            confidence_level="low",
            confidence_explanation=(
                "Confidence is low because the reasoning engine did "
                "not identify a supported conclusion."
            ),
            limitations=[
                gap.description
                for gap in result.evidence.gaps
            ],
            limitations_explanation=(
                "Additional relevant and corroborating evidence is "
                "required before Sentinel can form a conclusion."
            ),
            missing_information=[
                gap.description
                for gap in result.evidence.gaps
            ],
            recommended_next_step=(
                "Collect additional evidence and repeat the "
                "reasoning operation."
            ),
            next_step_explanation=(
                "Provide more directly relevant or independently "
                "corroborating evidence."
            ),
            source_count=result.evidence.source_count,
            document_count=(
                result.evidence.document_count
            ),
            domain_count=result.evidence.domain_count,
            reasoning_trace=result.reasoning_trace,
            status=result.status,
        )

    def format(
        self,
        result: ReasoningResult,
    ) -> FormattedReasoningResponse:
        """
        Format one completed reasoning operation.

        The returned confidence, conclusion, limitations, evidence
        counts, and next step are copied from the authoritative result.
        """

        if result.conclusion is None:
            return self._fallback_response(result)

        completion = self.client.chat.completions.parse(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": self._system_message(),
                },
                {
                    "role": "user",
                    "content": (
                        "Format the following completed SentinelAI "
                        "reasoning result. Preserve every authoritative "
                        "judgment exactly.\n\n"
                        f"{self._formatter_payload(result)}"
                    ),
                },
            ],
            response_format=ReasoningNarrative,
            temperature=0.2,
        )

        message = completion.choices[0].message

        if message.refusal:
            raise RuntimeError(
                "Sentinel's reasoning formatter refused the "
                f"request: {message.refusal}"
            )

        narrative = message.parsed

        if narrative is None:
            raise RuntimeError(
                "Sentinel's reasoning formatter returned no "
                "structured narrative."
            )

        conclusion = result.conclusion

        return FormattedReasoningResponse(
            answer=narrative.answer,
            conclusion=conclusion.statement,
            evidence_explanation=(
                narrative.evidence_explanation
            ),
            confidence_score=(
                conclusion.confidence.score
            ),
            confidence_level=(
                conclusion.confidence.level.value
            ),
            confidence_explanation=(
                narrative.confidence_explanation
            ),
            limitations=conclusion.limitations,
            limitations_explanation=(
                narrative.limitations_explanation
            ),
            missing_information=(
                conclusion.missing_information
            ),
            recommended_next_step=(
                conclusion.recommended_next_step
            ),
            next_step_explanation=(
                narrative.next_step_explanation
            ),
            source_count=result.evidence.source_count,
            document_count=(
                result.evidence.document_count
            ),
            domain_count=result.evidence.domain_count,
            reasoning_trace=result.reasoning_trace,
            status=result.status,
        )


class ReasoningResultPayload(BaseModel):
    """
    Internal serialization boundary for formatter input.
    """

    payload: dict
