"""
Explainable confidence assessment for SentinelAI planning.

Planning confidence is derived from inspectable planning characteristics
rather than copied directly from reasoning confidence or generated by an
LLM.

The score represents the viability and completeness of a proposed plan.

It does not guarantee successful execution.

Factors include:

- strength of the reasoning foundation,
- strategy suitability,
- step completeness,
- dependency readiness,
- assumption burden,
- risk exposure,
- unresolved planning conditions,
- human-approval coverage.

This service evaluates a plan.

It does not select strategies, generate steps, identify new risks,
format communication, or execute actions.
"""

from __future__ import annotations

from statistics import mean

from app.services.cognition.planning.models import (
    PlanningConfidence,
    PlanningConfidenceFactor,
    PlanningConfidenceLevel,
    PlanningContext,
    PlanningRiskAnalysis,
    PlanningStep,
    PlanningStrategy,
    RiskLevel,
)


class PlanningConfidenceEngine:
    """
    Calculate transparent confidence in a proposed plan.

    Every factor produces:

    - a bounded contribution,
    - a human-readable explanation,
    - an inspectable effect on the final score.
    """

    @staticmethod
    def _clamp(
        value: float,
        minimum: float = 0.0,
        maximum: float = 1.0,
    ) -> float:
        return max(
            minimum,
            min(value, maximum),
        )

    @staticmethod
    def _confidence_level(
        score: float,
    ) -> PlanningConfidenceLevel:
        if score >= 0.80:
            return PlanningConfidenceLevel.HIGH

        if score >= 0.60:
            return PlanningConfidenceLevel.MODERATE

        return PlanningConfidenceLevel.LOW

    @staticmethod
    def _reasoning_score(
        context: PlanningContext,
    ) -> float:
        """
        Return the authoritative reasoning-confidence score.

        Planning confidence may use reasoning confidence as one factor,
        but never treats it as the final planning-confidence result.
        """

        conclusion = context.reasoning_result.conclusion

        if conclusion is None:
            return 0.0

        return conclusion.confidence.score

    @classmethod
    def _reasoning_factor(
        cls,
        context: PlanningContext,
    ) -> PlanningConfidenceFactor:
        score = cls._clamp(
            cls._reasoning_score(context)
        )

        contribution = score * 0.25

        return PlanningConfidenceFactor(
            name="reasoning_strength",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                "The authoritative reasoning foundation has a "
                f"confidence score of {score:.3f}."
            ),
        )

    @classmethod
    def _strategy_factor(
        cls,
        strategy: PlanningStrategy | None,
    ) -> PlanningConfidenceFactor:
        if strategy is None:
            score = 0.0
            explanation = (
                "No supported planning strategy was selected."
            )
        else:
            score = cls._clamp(
                strategy.suitability_score
            )
            explanation = (
                f"The selected strategy has a deterministic "
                f"suitability score of {score:.3f}."
            )

        contribution = score * 0.20

        return PlanningConfidenceFactor(
            name="strategy_suitability",
            contribution=round(
                contribution,
                4,
            ),
            explanation=explanation,
        )

    @classmethod
    def _step_completeness_factor(
        cls,
        steps: list[PlanningStep],
    ) -> PlanningConfidenceFactor:
        """
        Evaluate whether the plan contains inspectable, verifiable steps.
        """

        if not steps:
            return PlanningConfidenceFactor(
                name="step_completeness",
                contribution=0.0,
                explanation=(
                    "The proposed plan contains no planning steps."
                ),
            )

        criteria_coverage = mean(
            1.0 if step.completion_criteria else 0.0
            for step in steps
        )

        rationale_coverage = mean(
            1.0 if step.rationale.strip() else 0.0
            for step in steps
        )

        sequence_values = sorted(
            step.sequence
            for step in steps
        )

        expected_sequences = list(
            range(
                1,
                len(steps) + 1,
            )
        )

        sequence_integrity = (
            1.0
            if sequence_values == expected_sequences
            else 0.0
        )

        completeness_score = (
            criteria_coverage * 0.45
            + rationale_coverage * 0.35
            + sequence_integrity * 0.20
        )

        contribution = (
            cls._clamp(completeness_score)
            * 0.20
        )

        return PlanningConfidenceFactor(
            name="step_completeness",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                f"The plan contains {len(steps)} ordered step"
                f"{'' if len(steps) == 1 else 's'}; "
                f"{criteria_coverage:.0%} include completion criteria, "
                f"{rationale_coverage:.0%} include rationale, and "
                f"sequence integrity is "
                f"{'valid' if sequence_integrity else 'invalid'}."
            ),
        )

    @classmethod
    def _dependency_factor(
        cls,
        analysis: PlanningRiskAnalysis,
    ) -> PlanningConfidenceFactor:
        dependencies = analysis.dependencies

        if not dependencies:
            return PlanningConfidenceFactor(
                name="dependency_readiness",
                contribution=0.10,
                explanation=(
                    "No explicit planning dependencies remain to be "
                    "verified."
                ),
            )

        satisfied_count = sum(
            1
            for dependency in dependencies
            if dependency.satisfied
        )

        readiness_ratio = (
            satisfied_count / len(dependencies)
        )

        contribution = (
            cls._clamp(readiness_ratio)
            * 0.10
        )

        return PlanningConfidenceFactor(
            name="dependency_readiness",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                f"{satisfied_count} of {len(dependencies)} planning "
                "dependencies are currently marked as satisfied."
            ),
        )

    @classmethod
    def _approval_factor(
        cls,
        steps: list[PlanningStep],
    ) -> PlanningConfidenceFactor:
        if not steps:
            coverage = 0.0
        else:
            coverage = mean(
                1.0
                if step.requires_human_approval
                else 0.0
                for step in steps
            )

        contribution = (
            cls._clamp(coverage)
            * 0.10
        )

        return PlanningConfidenceFactor(
            name="human_approval_coverage",
            contribution=round(
                contribution,
                4,
            ),
            explanation=(
                f"{coverage:.0%} of proposed steps are explicitly "
                "gated by human approval."
            ),
        )

    @staticmethod
    def _assumption_factor(
        analysis: PlanningRiskAnalysis,
    ) -> PlanningConfidenceFactor:
        unverified_count = sum(
            1
            for assumption in analysis.assumptions
            if not assumption.verified
        )

        penalty = min(
            unverified_count * 0.04,
            0.20,
        )

        return PlanningConfidenceFactor(
            name="assumption_burden",
            contribution=round(
                -penalty,
                4,
            ),
            explanation=(
                f"{unverified_count} unverified planning assumption"
                f"{'' if unverified_count == 1 else 's'} remain."
            ),
        )

    @staticmethod
    def _risk_weight(
        likelihood: RiskLevel,
        impact: RiskLevel,
    ) -> float:
        likelihood_weights = {
            RiskLevel.LOW: 0.20,
            RiskLevel.MODERATE: 0.50,
            RiskLevel.HIGH: 0.80,
            RiskLevel.CRITICAL: 1.00,
        }

        impact_weights = {
            RiskLevel.LOW: 0.20,
            RiskLevel.MODERATE: 0.50,
            RiskLevel.HIGH: 0.80,
            RiskLevel.CRITICAL: 1.00,
        }

        return (
            likelihood_weights[likelihood]
            * impact_weights[impact]
        )

    @classmethod
    def _risk_factor(
        cls,
        analysis: PlanningRiskAnalysis,
    ) -> PlanningConfidenceFactor:
        if not analysis.risks:
            return PlanningConfidenceFactor(
                name="risk_exposure",
                contribution=0.0,
                explanation=(
                    "No explicit planning risks were identified."
                ),
            )

        average_risk = mean(
            cls._risk_weight(
                risk.likelihood,
                risk.impact,
            )
            for risk in analysis.risks
        )

        penalty = min(
            average_risk * 0.22,
            0.22,
        )

        high_impact_count = sum(
            1
            for risk in analysis.risks
            if risk.impact in {
                RiskLevel.HIGH,
                RiskLevel.CRITICAL,
            }
        )

        return PlanningConfidenceFactor(
            name="risk_exposure",
            contribution=round(
                -penalty,
                4,
            ),
            explanation=(
                f"The analysis identified {len(analysis.risks)} risk"
                f"{'' if len(analysis.risks) == 1 else 's'}, including "
                f"{high_impact_count} with high or critical impact. "
                f"Average weighted exposure is {average_risk:.3f}."
            ),
        )

    @staticmethod
    def _unresolved_factor(
        analysis: PlanningRiskAnalysis,
    ) -> PlanningConfidenceFactor:
        unresolved_count = len(
            analysis.unresolved_conditions
        )

        penalty = min(
            unresolved_count * 0.025,
            0.20,
        )

        return PlanningConfidenceFactor(
            name="unresolved_conditions",
            contribution=round(
                -penalty,
                4,
            ),
            explanation=(
                f"{unresolved_count} unresolved planning condition"
                f"{'' if unresolved_count == 1 else 's'} remain."
            ),
        )

    @staticmethod
    def _uncertainty(
        *,
        context: PlanningContext,
        strategy: PlanningStrategy | None,
        steps: list[PlanningStep],
        analysis: PlanningRiskAnalysis,
    ) -> list[str]:
        uncertainty: list[str] = []

        conclusion = context.reasoning_result.conclusion

        if conclusion is None:
            uncertainty.append(
                "No authoritative reasoning conclusion is available."
            )
        else:
            uncertainty.extend(
                conclusion.limitations
            )
            uncertainty.extend(
                conclusion.missing_information
            )
            uncertainty.extend(
                conclusion.confidence.uncertainty
            )

        if strategy is None:
            uncertainty.append(
                "No supported planning strategy was selected."
            )

        if not steps:
            uncertainty.append(
                "No ordered planning steps were produced."
            )

        uncertainty.extend(
            analysis.unresolved_conditions
        )

        deduplicated: list[str] = []
        seen: set[str] = set()

        for statement in uncertainty:
            cleaned = str(statement).strip()

            if not cleaned:
                continue

            identity = cleaned.casefold()

            if identity in seen:
                continue

            seen.add(identity)
            deduplicated.append(cleaned)

        return deduplicated

    @staticmethod
    def _basis(
        *,
        score: float,
        strategy: PlanningStrategy | None,
        steps: list[PlanningStep],
        analysis: PlanningRiskAnalysis,
    ) -> str:
        strategy_name = (
            strategy.name
            if strategy is not None
            else "no selected strategy"
        )

        return (
            f"Planning confidence is based on {strategy_name}, "
            f"{len(steps)} proposed step"
            f"{'' if len(steps) == 1 else 's'}, "
            f"{len(analysis.dependencies)} dependenc"
            f"{'y' if len(analysis.dependencies) == 1 else 'ies'}, "
            f"{len(analysis.assumptions)} assumption"
            f"{'' if len(analysis.assumptions) == 1 else 's'}, "
            f"{len(analysis.risks)} risk"
            f"{'' if len(analysis.risks) == 1 else 's'}, and "
            f"{len(analysis.unresolved_conditions)} unresolved condition"
            f"{'' if len(analysis.unresolved_conditions) == 1 else 's'}. "
            f"The resulting viability score is {score:.3f}."
        )

    def assess(
        self,
        *,
        context: PlanningContext,
        strategy: PlanningStrategy | None,
        steps: list[PlanningStep],
        risk_analysis: PlanningRiskAnalysis,
    ) -> PlanningConfidence:
        """
        Produce one explainable planning-confidence assessment.

        Scores are derived entirely from structured reasoning, planning,
        and risk-analysis contracts.
        """

        factors = [
            self._reasoning_factor(context),
            self._strategy_factor(strategy),
            self._step_completeness_factor(
                steps
            ),
            self._dependency_factor(
                risk_analysis
            ),
            self._approval_factor(steps),
            self._assumption_factor(
                risk_analysis
            ),
            self._risk_factor(
                risk_analysis
            ),
            self._unresolved_factor(
                risk_analysis
            ),
        ]

        score = round(
            self._clamp(
                sum(
                    factor.contribution
                    for factor in factors
                )
            ),
            3,
        )

        return PlanningConfidence(
            score=score,
            level=self._confidence_level(
                score
            ),
            basis=self._basis(
                score=score,
                strategy=strategy,
                steps=steps,
                analysis=risk_analysis,
            ),
            factors=factors,
            uncertainty=self._uncertainty(
                context=context,
                strategy=strategy,
                steps=steps,
                analysis=risk_analysis,
            ),
        )
