"""
LLM-based communication formatter for SentinelAI planning results.

The planning process is already complete before this service runs.

The formatter may:

- improve clarity,
- organize the plan,
- translate structured planning into readable language.

The formatter may not:

- change the objective,
- change the selected strategy,
- add, remove, or reorder steps,
- invent dependencies, assumptions, or risks,
- modify planning confidence,
- alter success criteria,
- imply that proposed actions were executed.

Sentinel plans first and communicates second.
"""

from __future__ import annotations

import os

from dotenv import load_dotenv
from openai import OpenAI
from pydantic import BaseModel, Field

from app.services.cognition.planning.models import (
    PlanningResult,
)


load_dotenv()


class PlanningNarrative(BaseModel):
    """
    Structured prose generated by the communication layer.

    These fields explain an authoritative PlanningResult but do not
    replace or modify its strategy, steps, risks, confidence, or status.
    """

    answer: str = Field(
        description=(
            "A concise overview of the authoritative proposed plan. "
            "Do not imply that any proposed step has been executed."
        )
    )

    strategy_explanation: str = Field(
        description=(
            "A clear explanation of the selected strategy and its "
            "recorded rationale. Do not select a different strategy."
        )
    )

    steps_explanation: str = Field(
        description=(
            "A readable presentation of the existing ordered steps. "
            "Do not add, remove, merge, split, or reorder steps."
        )
    )

    risk_explanation: str = Field(
        description=(
            "A concise explanation of the recorded dependencies, "
            "assumptions, risks, mitigations, contingencies, and "
            "planning uncertainty."
        )
    )

    success_explanation: str = Field(
        description=(
            "A clear presentation of the recorded success criteria "
            "and the conditions required before the plan can be "
            "considered complete."
        )
    )


class FormattedPlanningResponse(BaseModel):
    """
    Final communication response returned after formatting.

    Authoritative planning fields are copied directly from the original
    PlanningResult. Only the narrative fields are model-generated.
    """

    answer: str

    objective: str

    strategy: str | None = None

    strategy_explanation: str

    steps_explanation: str

    risk_explanation: str

    success_explanation: str

    step_count: int = Field(
        default=0,
        ge=0,
    )

    dependency_count: int = Field(
        default=0,
        ge=0,
    )

    assumption_count: int = Field(
        default=0,
        ge=0,
    )

    risk_count: int = Field(
        default=0,
        ge=0,
    )

    confidence_score: float = Field(
        ge=0.0,
        le=1.0,
    )

    confidence_level: str

    estimated_complexity: str

    planning_trace: list[str] = Field(
        default_factory=list,
    )

    status: str


class PlanningFormatter:
    """
    Convert a completed PlanningResult into professional language.

    This service is intentionally downstream from the deterministic
    planning engine. It cannot change Sentinel's authoritative plan.
    """

    def __init__(
        self,
        *,
        model: str = "gpt-4.1-mini",
    ):
        api_key = os.getenv("OPENAI_API_KEY")

        if not api_key:
            raise RuntimeError(
                "OPENAI_API_KEY is not configured."
            )

        self.client = OpenAI(
            api_key=api_key,
        )

        self.model = model

    @staticmethod
    def _system_message() -> str:
        return (
            "You are SentinelAI's planning communication layer. "
            "The planning operation has already been completed by "
            "deterministic services. Your only responsibility is to "
            "explain the supplied structured plan clearly and "
            "professionally. Do not introduce new facts, assumptions, "
            "strategies, steps, dependencies, risks, confidence values, "
            "success criteria, or recommended actions. Do not reorder "
            "or merge steps. Preserve uncertainty and human-approval "
            "requirements. Never imply that proposed actions were "
            "executed. If planning is blocked or reasoning is "
            "insufficient, state that plainly."
        )

    @staticmethod
    def _formatter_payload(
        result: PlanningResult,
    ) -> str:
        """
        Serialize only the information needed for communication.

        Internal implementation details and hidden processing state are
        never sent to the formatter.
        """

        payload = {
            "objective": result.objective.model_dump(),
            "reasoning_basis": (
                result.reasoning_basis.model_dump()
            ),
            "strategy": (
                result.strategy.model_dump()
                if result.strategy is not None
                else None
            ),
            "steps": [
                step.model_dump()
                for step in result.steps
            ],
            "dependencies": [
                dependency.model_dump()
                for dependency in result.dependencies
            ],
            "assumptions": [
                assumption.model_dump()
                for assumption in result.assumptions
            ],
            "constraints": result.constraints,
            "risks": [
                risk.model_dump()
                for risk in result.risks
            ],
            "success_criteria": (
                result.success_criteria
            ),
            "estimated_complexity": (
                result.estimated_complexity.value
            ),
            "confidence": {
                "score": result.confidence.score,
                "level": result.confidence.level.value,
                "basis": result.confidence.basis,
                "factors": [
                    factor.model_dump()
                    for factor in result.confidence.factors
                ],
                "uncertainty": (
                    result.confidence.uncertainty
                ),
            },
            "planning_trace": result.planning_trace,
            "status": result.status.value,
        }

        return PlanningResultPayload(
            payload=payload
        ).model_dump_json(indent=2)

    @staticmethod
    def _fallback_response(
        result: PlanningResult,
    ) -> FormattedPlanningResponse:
        """
        Produce deterministic communication when no actionable plan exists.

        Insufficient reasoning or a blocked plan does not require an LLM
        call.
        """

        if result.reasoning_basis.conclusion is None:
            answer = (
                "Sentinel could not produce a supported plan because "
                "the available reasoning did not contain a supported "
                "conclusion."
            )

            strategy_explanation = (
                "No strategy was selected because planning requires "
                "a completed, evidence-supported reasoning result."
            )

            steps_explanation = (
                "No planning steps were produced."
            )

            risk_explanation = (
                "The primary limitation is the absence of a supported "
                "reasoning foundation. Additional relevant evidence is "
                "required before planning can proceed."
            )

            success_explanation = (
                "Planning may be attempted again after Sentinel produces "
                "a supported reasoning conclusion."
            )

        else:
            answer = (
                "Sentinel could not produce a complete supported plan "
                "from the available planning conditions."
            )

            strategy_explanation = (
                "No usable strategy was selected, or the selected "
                "strategy could not be decomposed into a viable plan."
            )

            steps_explanation = (
                f"{len(result.steps)} proposed planning step"
                f"{'' if len(result.steps) == 1 else 's'} were produced, "
                "but the planning operation remains blocked."
            )

            risk_explanation = (
                f"The plan contains {len(result.risks)} recorded risk"
                f"{'' if len(result.risks) == 1 else 's'} and "
                f"{len(result.confidence.uncertainty)} unresolved "
                "planning condition"
                f"{'' if len(result.confidence.uncertainty) == 1 else 's'}."
            )

            success_explanation = (
                "Resolve the recorded planning uncertainty and repeat "
                "the planning operation before seeking approval."
            )

        return FormattedPlanningResponse(
            answer=answer,
            objective=result.objective.statement,
            strategy=(
                result.strategy.name
                if result.strategy is not None
                else None
            ),
            strategy_explanation=(
                strategy_explanation
            ),
            steps_explanation=steps_explanation,
            risk_explanation=risk_explanation,
            success_explanation=success_explanation,
            step_count=len(result.steps),
            dependency_count=len(
                result.dependencies
            ),
            assumption_count=len(
                result.assumptions
            ),
            risk_count=len(result.risks),
            confidence_score=(
                result.confidence.score
            ),
            confidence_level=(
                result.confidence.level.value
            ),
            estimated_complexity=(
                result.estimated_complexity.value
            ),
            planning_trace=result.planning_trace,
            status=result.status.value,
        )

    def format(
        self,
        result: PlanningResult,
    ) -> FormattedPlanningResponse:
        """
        Format one completed planning operation.

        The returned objective, strategy, counts, confidence, complexity,
        trace, and status are copied from the authoritative result.
        """

        if (
            result.strategy is None
            or not result.steps
        ):
            return self._fallback_response(result)

        completion = self.client.chat.completions.parse(
            model=self.model,
            messages=[
                {
                    "role": "system",
                    "content": self._system_message(),
                },
                {
                    "role": "user",
                    "content": (
                        "Format the following completed SentinelAI "
                        "planning result. Preserve every authoritative "
                        "planning judgment exactly.\n\n"
                        f"{self._formatter_payload(result)}"
                    ),
                },
            ],
            response_format=PlanningNarrative,
            temperature=0.2,
        )

        message = completion.choices[0].message

        if message.refusal:
            raise RuntimeError(
                "Sentinel's planning formatter refused the "
                f"request: {message.refusal}"
            )

        narrative = message.parsed

        if narrative is None:
            raise RuntimeError(
                "Sentinel's planning formatter returned no "
                "structured narrative."
            )

        strategy = result.strategy

        return FormattedPlanningResponse(
            answer=narrative.answer,
            objective=result.objective.statement,
            strategy=strategy.name,
            strategy_explanation=(
                narrative.strategy_explanation
            ),
            steps_explanation=(
                narrative.steps_explanation
            ),
            risk_explanation=(
                narrative.risk_explanation
            ),
            success_explanation=(
                narrative.success_explanation
            ),
            step_count=len(result.steps),
            dependency_count=len(
                result.dependencies
            ),
            assumption_count=len(
                result.assumptions
            ),
            risk_count=len(result.risks),
            confidence_score=(
                result.confidence.score
            ),
            confidence_level=(
                result.confidence.level.value
            ),
            estimated_complexity=(
                result.estimated_complexity.value
            ),
            planning_trace=result.planning_trace,
            status=result.status.value,
        )


class PlanningResultPayload(BaseModel):
    """
    Internal serialization boundary for formatter input.
    """

    payload: dict
